spring:
  application:
    name: demo-load-testing-eureka-server
  output:
    ansi:
      enabled: ALWAYS
server:
  port: 9000
eureka:
  server:
    enableSelfPreservation: false
    renewalPercentThreshold: 0.49
  instance:
    hostname: peer1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/

